version: '2'
services:
  teamcity-server:
    image: teamcity-server:local-nanoserver-1809
    ports:
     - "8112:8111"
 
  teamcity-minimal-agent:
    image: teamcity-minimal-agent:local-nanoserver-1809
    environment:
      - SERVER_URL=teamcity-server:8111

  teamcity-agent:
    image: teamcity-agent:local-nanoserver-1809
    environment:
      - SERVER_URL=teamcity-server:8111

  teamcity-core-agent:
    image: teamcity-agent:local-windowsservercore-1809
    environment:
      - SERVER_URL=teamcity-server:8111